name: Release

on:
  workflow_dispatch:
  push:

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: ./photo
      - name: Init git
        run: |
             git config --global user.email "iRealColors@outlook.de" 
             git config --global user.name "YoumiHa"
      - name: Set up version
        run: echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Create tag
        run: git tag -a ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
      - name: Build
        run: |
             zip -r photo.zip ./photo
      - name: Push tag
        run: git push origin ${{ env.VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Lip-Sese
          files: ./photo.zip
