name: Release

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: ./
      - name: Set up version
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

      - name: Create tag
        run: git tag -a ${{ env.RELEASE_VERSION }} -m "Release ${{ env.RELEASE_VERSION }}"

      - name: Push tag
        run: git push origin ${{ env.RELEASE_VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Lip-Sese
